[tool.poetry]
name = "pymedphys"
version = "0.12.0dev1"
readme = "README.rst"
description = "Medical Physics library"
authors = [
    "PyMedPhys Contributors <developers@pymedphys.com>",
    "Simon Biggs <sbiggs@pymedphys.com>",
    "Matthew Jennings <mjennings@pymedphys.com>>",
    "Phillip Chlap",
    "Paul King <pking@pymedphys.com>",
    "Matthew Sobolewski <msobolewski@pymedphys.com>",
    "Jacob McAloney",
    "Pedro Martinez"
]
license = "AGPL-3.0+"
homepage = "https://pymedphys.com"
repository = "https://github.com/pymedphys/pymedphys"
documentation = "https://pymedphys.com"
classifiers = [
    "Development Status :: 4 - Beta",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
    "Topic :: Scientific/Engineering :: Physics",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Healthcare Industry",
]

[tool.poetry.dependencies]
python = "^3.7"

attrs = "*"
keyring = "*"
packaging = "*"

numpy = "^1.12"
matplotlib = "*"
scipy = "*"
pandas = "*"

pydicom = "*"

pymssql = "*"
shapely = "*"


tqdm = { version = "*", optional = true }
python_dateutil = { version = "*", optional = true }
PyYAML = { version = "*", optional = true }

Pillow = { version = "*", optional = true }
imageio = { version = "*", optional = true }
scikit-image = { version = "*", optional = true }


[tool.poetry.dev-dependencies]
pytest = "^5.1"
# pytest-cov = "^2.5"
pytest-sugar = "^0.9.2"
# pytest-mock = "^1.9"
black = { version = "^19.3b0"}
pre-commit = "^1.10"
tox = "^3.0"
mypy = "^0.720.0"
pylint = "^2.3"
pytest-pylint = "^0.14.1"
ipykernel = "*"
ipython = "*"
jupyter_client = "*"
m2r = "*"
nbsphinx = "*"
sphinx-autobuild = "*"
sphinxcontrib-napoleon = "*"
sphinx = ">= 1.4, < 1.8"
sphinx-argparse = "*"
sphinx-rtd-theme = "^0.4.3"
rope = "^0.14.0"

[tool.poetry.extras]
docs = [
    "nbsphinx", "m2r", "sphinx-autobuild", "sphinxcontrib-napoleon", "sphinx",
    "sphinx-argparse", "sphinx-rtd-theme"
]

labs = [
    "tqdm", "python_dateutil", "PyYAML", "Pillow", "imageio", "scikit-image"
]

pytest = [
    "pytest", "pytest-sugar"
]

pylint = [
    "pylint", "pytest-pylint", "pytest", "pytest-sugar"
]






[tool.poetry.scripts]
pymedphys = "pymedphys.cli.main:pymedphys_cli"

[build-system]
requires = ["poetry >= 0.12", "setuptools >= 35.0.2", "wheel >= 0.29.0"]
build-backend = "poetry.masonry.api"
