[tool.poetry]
name = "pymedphys"
version = "0.12.0dev1"
readme = "README.rst"
authors = [
    "Simon Biggs <me@simonbiggs.net>",
    "Matthew Jennings <Centrus.007@gmail.com>",
    "Phillip Chlap",
    "Paul King <king.r.paul@gmail.com>",
    "Matthew Sobolewski",
    "Jacob McAloney",
    "Pedro Martinez"
]
license = "AGPL-3.0+"
homepage = "https://pymedphys.com"
repository = "https://github.com/pymedphys/pymedphys"
documentation = "https://pymedphys.com"
classifiers = [
    "Development Status :: 4 - Beta",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
    "Topic :: Scientific/Engineering :: Physics",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Healthcare Industry",
]

[tool.poetry.dependencies]
python = "^3.7"

attrs = "*"
keyring = "*"
packaging = "*"

tqdm = "*"
python_dateutil = "*"
PyYAML = "*"

numpy = "^1.12"
matplotlib = "*"
scipy = "*"
pandas = "*"

pydicom = "*"

Pillow = "*"
imageio = "*"
scikit-image = "*"

pymssql = "*"

shapely = [
    { version = "*", url = "https://github.com/pymedphys/pymedphys/releases/download/v0.11.0/Shapely-1.6.4.post2-cp37-cp37m-win32.whl", system = "Windows", machine = "i386" },
    { version = "*", url = "https://github.com/pymedphys/pymedphys/releases/download/v0.11.0/Shapely-1.6.4.post2-cp37-cp37m-win_amd64.whl", system = "Windows", machine = "x86_64" },
    { version = "*", system = "Linux" },
    { version = "*", system = "macOS" }
]

[tool.poetry.dev-dependencies]
pytest = "^5.1"
pytest-cov = "^2.5"
pytest-sugar = "^0.9.2"
pytest-mock = "^1.9"
black = { version = "^19.3b0"}
pre-commit = "^1.10"
tox = "^3.0"
mypy = "^0.720.0"
pylint = "^2.3"
pytest-pylint = "^0.14.1"
ipykernel = "*"
ipython = "*"
jupyter_client = "*"
m2r = "*"
nbsphinx = "*"
sphinx-autobuild = "*"
sphinxcontrib-napoleon = "*"
sphinx = ">= 1.4, < 1.8"
sphinx-argparse = "*"
sphinx-rtd-theme = "^0.4.3"
rope = "^0.14.0"


[tool.poetry.scripts]
pymedphys = "pymedphys.cli.main:pymedphys_cli"

[build-system]
requires = ["poetry >= 0.12", "setuptools >= 35.0.2", "wheel >= 0.29.0"]
build-backend = "poetry.masonry.api"
